// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTodoTask = "todo_tasks"

// TodoTask mapped from table <todo_tasks>
type TodoTask struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskName           string    `gorm:"column:task_name;not null" json:"task_name"`
	TaskDescription    string    `gorm:"column:task_description" json:"task_description"`
	TaskStatus         string    `gorm:"column:task_status;not null" json:"task_status"`
	TaskPriority       string    `gorm:"column:task_priority;not null" json:"task_priority"`
	TaskDeadline       time.Time `gorm:"column:task_deadline" json:"task_deadline"`
	TaskAssignee       string    `gorm:"column:task_assignee" json:"task_assignee"`
	TaskLabel          string    `gorm:"column:task_label" json:"task_label"`
	TaskReminder       time.Time `gorm:"column:task_reminder" json:"task_reminder"`
	TaskProgress       int32     `gorm:"column:task_progress" json:"task_progress"`
	TaskAttachments    string    `gorm:"column:task_attachments" json:"task_attachments"`
	TaskComments       string    `gorm:"column:task_comments" json:"task_comments"`
	TaskSubtasks       string    `gorm:"column:task_subtasks" json:"task_subtasks"`
	TaskCompletionTime time.Time `gorm:"column:task_completion_time" json:"task_completion_time"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName TodoTask's table name
func (*TodoTask) TableName() string {
	return TableNameTodoTask
}
