// Code generated by hertz generator.

package handler

import (
	"context"
	"example.com/m/dal"
	"example.com/m/model"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"time"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	err := dal.CreateTodoTask(&model.TodoTask{
		TaskName:           "sql",
		TaskStatus:         "todo",
		TaskPriority:       "high",
		TaskDeadline:       time.Now(),
		CreatedAt:          time.Now(),
		TaskReminder:       time.Now(),
		TaskCompletionTime: time.Now(),
	})
	if err != nil {
		return
	}
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}
